/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "inverse-surface": "#303030",
        "on-primary-fixed-variant": "#7c2e00",
        "on-secondary-fixed-variant": "#00458f",
        "tertiary-fixed-dim": "#e9c176",
        "tertiary-container": "#634705",
        "surface": "#fcf9f8",
        "on-secondary-fixed": "#001b3f",
        "error": "#ba1a1a",
        "on-tertiary-fixed-variant": "#5d4201",
        "on-secondary": "#ffffff",
        "background": "#fcf9f8",
        "tertiary": "#473100",
        "outline": "#737783",
        "on-tertiary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "on-surface-variant": "#424751",
        "on-primary-fixed": "#360f00",
        "primary-container": "#853100",
        "outline-variant": "#c2c6d3",
        "primary": "#602200",
        "on-primary": "#ffffff",
        "on-primary-container": "#ffa780",
        "on-background": "#1b1c1c",
        "surface-tint": "#a33e00",
        "on-surface": "#1b1c1c",
        "on-secondary-container": "#003c7e",
        "inverse-primary": "#ffb596",
        "surface-bright": "#fcf9f8",
        "surface-container-low": "#f6f3f2",
        "secondary-fixed-dim": "#abc7ff",
        "error-container": "#ffdad6",
        "surface-container": "#f0eded",
        "secondary-container": "#79a9fd",
        "surface-container-high": "#eae7e7",
        "secondary": "#255dad",
        "on-error-container": "#93000a",
        "secondary-fixed": "#d7e2ff",
        "tertiary-fixed": "#ffdea5",
        "inverse-on-surface": "#f3f0ef",
        "surface-variant": "#e4e2e1",
        "primary-fixed": "#ffdbcd",
        "surface-container-highest": "#e4e2e1",
        "on-tertiary-container": "#deb76d",
        "on-tertiary-fixed": "#261900",
        "surface-dim": "#dcd9d9",
        "primary-fixed-dim": "#ffb596",
        "on-error": "#ffffff"
      },
      "fontFamily": {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      }
    },
  },
  plugins: [],
}
